#!/bin/bash
service=$1
ip=$(curl -s https://api.ipify.org)
os="$(neofetch os)";            os="${os##*: }"
distro="$(neofetch distro)";   distro="${distro##*: }"
cpu="$(neofetch cpu --cpu_speed on --cpu_cores off)"; cpu="${cpu##*: }"
memory="$(neofetch memory)";   memory="${memory##*: }"
disk="$(neofetch disk)";       disk="${disk##*: }"
uptime="$(neofetch uptime)";   uptime="${uptime##*: }"
bandwidth=$(vnstat --oneline | cut -d ";" -f 15)

if [[ $service == "ssh" ]]; then
    ssh=$(systemctl is-active sshd)
    dropbear=$((echo >/dev/tcp/localhost/44) &>/dev/null && echo "active" || echo "inactive")
    squid=$(systemctl is-active squid)
    ssl=$(systemctl is-active stunnel4)
    socket=$((echo >/dev/tcp/localhost/80) &>/dev/null && echo "active" || echo "inactive")
    
    total_sshd=$(netstat -natp | awk "/$ip:22\y/ && /ESTABLISHED/ && /sshd/" | wc -l)
    total_dropbear=$(netstat -natp | awk "/$ip:44\y/ && /ESTABLISHED/ && /dropbear/" | wc -l)
    total_socket=$(netstat -natp | awk "/$ip:80\y/ && /ESTABLISHED/ && /python/" | wc -l)
    total_ssl=$(netstat -natp | awk "/$ip:443\y/ && /ESTABLISHED/ && /stunnel4/" | wc -l)
    totalssh=$((total_sshd + total_dropbear + total_socket + total_ssl))
    
    . /root/.ports

    output=$(cat <<EOF
{
 "service": "ssh protocol",
 "ip": "$ip",
 "users": "$totalssh",
 "bandwidth": "$bandwidth",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime",
 "ssh_port": "$ssh_port - $ssh",
 "dropbear_port": "$dropbear_port - $dropbear",
 "socket_port": "$socket_port - $socket",
 "squid_port": "$squid_port - $squid",
 "ssh_ssl_port": "$ssh_ssl_port - $ssl",
 "dropbear_ssl_port": "$dropbear_ssl_port - $ssl"
}
EOF
)
    echo "$output"

elif [[ $service == "hysteria" ]]; then
    udphysteria=$(systemctl is-active hysteria-server.service)
    squid=$(systemctl is-active squid)
    total_hysteria=$(netstat -natp | awk "/$ip:53/ && /ESTABLISHED/ && /hysteria/" | wc -l)
    
    . /root/.ports
    . /root/.db-base

    output=$(cat <<EOF
{
 "service": "openvpn protocol",
 "ip": "$ip",
 "users": "$totalovpn",
 "bandwidth": "$bandwidth",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime",
 "udp_hysteria": "$hysteria_port - $udphysteria",
 "squid_port": "$squid_port - $squid"
}
EOF
)

    mysql -u $DB_USER -p$DB_PASS -D $DB_NAME -h $DB_HOST -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', hysteria_status='$udphysteria', squid_status='$squid', hysteria_port='$hysteria_port', squid='$squid_port', hysteria_online='$total_hysteria' WHERE server_ip='$ip'"

elif [[ $service == "socksip" ]]; then
    udpSERVER=$(systemctl is-active UDPserver)
    squid=$(systemctl is-active squid)

    . /root/.ports
    . /root/.db-base

    mysql -u $DB_USER -p$DB_PASS -D $DB_NAME -h $DB_HOST -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', socksip_status='$udpSERVER', socksip_port='$socksip_port' WHERE server_ip='$ip'"

elif [[ $service == "openvpn" ]]; then
    tcpovpn=$(systemctl is-active openvpn@server2.service)
    udpovpn=$(systemctl is-active openvpn@server.service)
    udphysteria=$(systemctl is-active hysteria-server.service)
    squid=$(systemctl is-active squid)
    ssl=$(systemctl is-active stunnel4)
    socket=$((echo >/dev/tcp/localhost/80) &>/dev/null && echo "active" || echo "inactive")
    
    tcpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/tcpclient.log | wc -l)
    udpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/udpclient.log | wc -l)
    totalovpn=$((tcpusers + udpusers))
    total_hysteria=$(netstat -natp | awk "/$ip:53/ && /ESTABLISHED/ && /hysteria/" | wc -l)
    
    . /root/.ports
    . /etc/openvpn/login/config.sh

    output=$(cat <<EOF
{
 "service": "openvpn protocol",
 "ip": "$ip",
 "users": "$totalovpn",
 "bandwidth": "$bandwidth",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime",
 "udp_hysteria": "$hysteria_port - $udphysteria",
 "tcp_port": "$tcp_port - $tcpovpn",
 "udp_port": "$udp_port - $udpovpn",
 "socket_port": "$socket_port - $socket",
 "squid_port": "$squid_port - $squid",
 "tcp_ssl_port": "$tcp_ssl_port - $ssl",
 "udp_ssl_port": "$udp_ssl_port - $ssl"
}
EOF
)

    mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', tcpssl='$tcp_ssl_port', udpssl='$udp_ssl_port', tcp_status='$tcpovpn', hysteria_status='$udphysteria', udp_status='$udpovpn', ssl_status='$ssl', squid_status='$squid', socket_status='$socket', tcp='$tcp_port', udp='$udp_port', hysteria_port='$hysteria_port', squid='$squid_port', socket='$socket_port', online='$totalovpn', hysteria_online='$total_hysteria' WHERE server_ip='$ip'"

elif [[ $service == "aio" ]]; then
    tcpovpn=$(systemctl is-active openvpn@server2.service)
    udpovpn=$(systemctl is-active openvpn@server.service)
    udphysteria=$(systemctl is-active hysteria-server.service)
    xray=$(systemctl is-active xray.service)
    slowdns=$(systemctl is-active server-sldns.service)
    sshd=$(systemctl is-active sshd)
    dropbear=$(systemctl is-active dropbear)
    squid=$(systemctl is-active squid)
    ssl=$(systemctl is-active stunnel4)
    socket=$((echo >/dev/tcp/localhost/80) &>/dev/null && echo "active" || echo "inactive")
    
    tcpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/tcpclient.log | wc -l)
    udpusers=$(sed -n -e '/^ROUTING_TABLE/p' /etc/openvpn/server/udpclient.log | wc -l)
    totalovpn=$((tcpusers + udpusers))
    
    total_sshd=$(netstat -natp | awk "/$ip:22/ && /ESTABLISHED/ && /sshd/" | wc -l)
    total_dropbear=$(netstat -natp | awk "/$ip:441/ && /ESTABLISHED/ && /dropbear/" | wc -l)
    total_socket1=$(netstat -natp | awk "/$ip:8000/ && /ESTABLISHED/ && /python/" | wc -l)
    total_socket2=$(netstat -natp | awk "/$ip:8001/ && /ESTABLISHED/ && /python/" | wc -l)
    total_socket3=$(netstat -natp | awk "/$ip:8002/ && /ESTABLISHED/ && /python/" | wc -l)
    total_sshssl=$(netstat -natp | awk "/$ip:445/ && /ESTABLISHED/ && /stunnel4/" | wc -l)
    totalssh=$((total_sshd + total_dropbear + total_socket1 + total_socket2 + total_socket3 + total_sshssl))
    total_hysteria=$(netstat -natp | awk "/$ip:53/ && /ESTABLISHED/ && /hysteria/" | wc -l)
    
    . /root/.ports
    . /etc/openvpn/login/config.sh

    mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', tcpssl='$tcp_ssl_port', udpssl='$udp_ssl_port', tcp_status='$tcpovpn', hysteria_status='$udphysteria', xray_status='$xray', ssh_online='$totalssh', slowdns_status='$slowdns', ssh_status='$sshd', dropbear_status='$dropbear', udp_status='$udpovpn', ssl_status='$ssl', squid_status='$squid', socket_status='$socket', tcp='$tcp_port', udp='$udp_port', hysteria_port='$hysteria_port', xray_port='$xray_port', slowdns_port='$slowdns_port', ssh_port='$ssh_port', dropbear_port='$dropbear_port', squid='$squid_port', socket='$socket_port', online='$totalovpn', hysteria_online='$total_hysteria' WHERE server_ip='$ip'"

elif [[ $service == "openconnect" ]]; then
    ocserv=$(systemctl is-active ocserv)
    udphysteria=$(systemctl is-active hysteria-server.service)
    squid=$(systemctl is-active squid)
    ssl=$(systemctl is-active stunnel4)
    socket=$((echo >/dev/tcp/localhost/80) &>/dev/null && echo "active" || echo "inactive")
    
    [ -f /root/.ports ] && . /root/.ports
    [ -f /root/.db-base ] && . /root/.db-base

    oc_json=$(occtl -j show users 2>/dev/null || sudo occtl -j show users 2>/dev/null)
    
    if [ -n "$oc_json" ] && echo "$oc_json" | jq empty 2>/dev/null; then
        totalocserv=$(echo "$oc_json" | jq '. | length' 2>/dev/null)
    else
        totalocserv=0
    fi
    totalocserv=${totalocserv:-0}
    
    total_hysteria=$(netstat -natp | awk "/$ip:53/ && /ESTABLISHED/ && /hysteria/" | wc -l)

    if [ -n "$DB_NAME" ]; then
        mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE users SET is_connected = 0, login_status = 'offline' WHERE protocol = 'openconnect'" 2>/dev/null

        if [ "$totalocserv" -gt 0 ]; then
            active_users=$(echo "$oc_json" | jq -r '.[].Username' 2>/dev/null)
            if [ -n "$active_users" ]; then
                tmp_users="/tmp/openconnect_active_users.txt"
                > "$tmp_users"
                for user in $active_users; do
                    if [ -n "$user" ] && [ "$user" != "null" ]; then
                        echo "'$user'" >> "$tmp_users"
                    fi
                done
                if [ -s "$tmp_users" ]; then
                    users_list=$(paste -sd, "$tmp_users")
                    mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE users SET is_connected = 1, login_status = 'online' WHERE username IN ($users_list)" 2>/dev/null
                fi
                rm -f "$tmp_users"
            fi
        fi

        mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', hysteria_status='$udphysteria', udp_status='$ocserv', ssl_status='$ssl', squid_status='$squid', socket_status='$socket', hysteria_port='$hysteria_port', squid='$squid_port', socket='$socket_port', online='$totalocserv', hysteria_online='$total_hysteria' WHERE server_ip='$ip'" 2>/dev/null
    fi

    output=$(cat <<EOF
{
 "service": "openconnect protocol",
 "ip": "$ip",
 "users": "$totalocserv",
 "bandwidth": "$bandwidth",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime",
 "udp_hysteria": "${hysteria_port:-none} - $udphysteria",
 "socket_port": "${socket_port:-80} - $socket",
 "squid_port": "${squid_port:-3128} - $squid",
 "tcp_ssl_port": "${tcp_ssl_port:-443} - $ssl",
 "udp_ssl_port": "${udp_ssl_port:-443} - $ssl"
}
EOF
)
    echo "$output"

elif [[ $service == "xray" ]]; then
    xray=$(systemctl is-active xray.service)
    nginx=$(systemctl is-active nginx)
    squid=$(systemctl is-active squid)

    . /root/.ports
    . /etc/xray/.db-base

    x_port=${xray_port:-10001}
    total_xray=$(ss -tnp | grep 'xray' | grep ":$x_port" | grep ESTAB | awk '{print $5}' | cut -d: -f1 | sort -u | wc -l)

    # 1. I-reset muna ang is_connected status sa users table sa simula
    mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE users SET is_connected = 0, login_status = 'offline'" 2>/dev/null

    log_file="/var/log/xray/access.log"
    if [ -f "$log_file" ] && [ "$total_xray" -gt 0 ]; then
        recent_logs=$(tail -n 300 "$log_file" | grep -E "accepted")
        active_users=$(echo "$recent_logs" | grep -oE 'email: [^[:space:]]+' | awk '{print $2}' | tr -d '"'\'' ' | sort -u)
        
        if [ -n "$active_users" ]; then
            # Kunin ang buong stats minsan lang
            all_stats=$(xray api statsquery --server=127.0.0.1:10000 -pattern "" -reset=false 2>/dev/null)

            for user in $active_users; do
                if [ -n "$user" ] && [ "$user" != "-" ]; then
                    user_ip=$(echo "$recent_logs" | grep "email: $user" | tail -n 1 | grep -oE 'from [0-9.]+' | awk '{print $2}')
                    user_ip=${user_ip:-$ip}

                    # 2. Mas siguruong pagkuha ng value gamit ang awk patungo sa eksaktong user key
                    up_bytes=$(echo "$all_stats" | awk -v u="$user" '$0 ~ "user>>>"u">>>traffic>>>uplink" {getline; print}' | grep -o '[0-9]*' | head -n 1)
                    down_bytes=$(echo "$all_stats" | awk -v u="$user" '$0 ~ "user>>>"u">>>traffic>>>downlink" {getline; print}' | grep -o '[0-9]*' | head -n 1)
                    
                    # Fallback kung sakaling maging blangko
                    up_bytes=${up_bytes:-0}
                    down_bytes=${down_bytes:-0}
                    
                    # Siguraduhing numero ang laman at hindi blangko
                    [[ "$up_bytes" =~ ^[0-9]+$ ]] || up_bytes=0
                    [[ "$down_bytes" =~ ^[0-9]+$ ]] || down_bytes=0

                    total_bandwidth=$((up_bytes + down_bytes))

                    current_time=$(date '+%Y-%m-%d %H:%M:%S')
                    current_ts=$(date +%s)

                    # 3. I-insert o i-update sa bandwidth_logs nang hindi nawawala ang data
                    sql_insert="INSERT INTO bandwidth_logs (server, server_ip, server_port, since_connected, username, ipaddress, bytes_received, bytes_sent, bandwidth, time, time_in, time_out, status, timestamp, category) VALUES ('Xray', '$ip', '$x_port', '$current_time', '$user', '$user_ip', '$down_bytes', '$up_bytes', '$total_bandwidth', '$current_time', '$current_time', '$current_time', 'online', '$current_ts', 'premium') ON DUPLICATE KEY UPDATE bytes_received='$down_bytes', bytes_sent='$up_bytes', bandwidth='$total_bandwidth', time='$current_time', status='online';"
                    
                    mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "$sql_insert" 2>/dev/null
                    
                    # 4. I-update ang users table
                    mysql --skip-ssl -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE users SET is_connected = 1, login_status = 'online', xray_upload = xray_upload + $up_bytes, xray_download = xray_download + $down_bytes WHERE user_name = '$user'" 2>/dev/null
                fi
            done
        fi
    fi

    # 5. I-update ang server status list
    mysql -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" -h "$DB_HOST" -e "UPDATE server_list SET cpu_model='$cpu', distro='$distro', memory='$memory', uptime='$uptime', disk='$disk', bandwidth='$bandwidth', os='$os', proto='$service', xray_tls='$xray_tls', xray_ntls='$xray_ntls', xray_status='$xray', squid_status='$squid', squid='$squid_port', xray_vmess='$vmess', xray_vless='$vless', xray_trojan='$trojan', xray_ss='$ss', xray_online='$total_xray' WHERE server_ip='$ip'" 2>/dev/null




elif [[ $service == "pptp" ]]; then
    pptpd=$(systemctl is-active pptpd)

    output=$(cat <<EOF
{
 "service": "pptp protocol",
 "ip": "$ip",
 "bandwidth": "$bandwidth",
 "pptpd": "$pptpd",
 "os": "$os",
 "distro": "$distro",
 "cpu": "$cpu",
 "memory": "$memory",
 "disk": "$disk",
 "uptime": "$uptime"
}
EOF
)
    echo "$output"

elif [[ $service == "reboot" ]]; then
    sudo shutdown -r now
fi
